    package com.example.myapplication

import com.example.myapplication.Const.Constant

enum class EnumFlag( val draw:Int, val number:Int) {
    AUD(R.drawable.australia,1),
    USD(R.drawable.usa,5),
    AZN(R.drawable.azerbaijan,0),
    EUR(R.drawable.ic_european_union,6),
    RUB(R.drawable.ic_flag_of_russia__1_,17),
    BGN(R.drawable.bulgaria,2),
    UAH(R.drawable.flag_belarusi,3),
    DKK(R.drawable.flag_belarusi,4),
    PLN(R.drawable.flag_belarusi,7),
    JPY(R.drawable.flag_belarusi,8),
    IRR(R.drawable.flag_belarusi,9),
    ISK(R.drawable.flag_belarusi,10),
    CAD(R.drawable.flag_belarusi,11),
    CNY(R.drawable.flag_belarusi,12),
    KWD(R.drawable.flag_belarusi,13),
    MDL(R.drawable.flag_belarusi,14),
    NZD(R.drawable.flag_belarusi,15),
    NOK(R.drawable.flag_belarusi,16),
    XDR(R.drawable.flag_belarusi,18),
    SGD(R.drawable.flag_belarusi,19),
    KGS(R.drawable.flag_belarusi,20),
    KZT(R.drawable.flag_belarusi,21),
    TRY(R.drawable.flag_belarusi,22),
    GBP(R.drawable.flag_belarusi,23),
    CZK(R.drawable.flag_belarusi,24),
    SEK(R.drawable.flag_belarusi,25),
    CHF(R.drawable.ic_flag_of_russia__1_,26),
    BYN(R.drawable.flag_belarusi,0),
    AMD(R.drawable.ic_flag_of_russia__1_,0),
    BRL(R.drawable.ic_flag_of_russia__1_,0),
    HUF(R.drawable.ic_flag_of_russia__1_,0),
    HKD(R.drawable.ic_flag_of_russia__1_,0),
    INR(R.drawable.ic_flag_of_russia__1_,0),
    RON(R.drawable.ic_flag_of_russia__1_,0),
    TJS(R.drawable.ic_flag_of_russia__1_,0),
    TMT(R.drawable.ic_flag_of_russia__1_,0),
    UZS(R.drawable.ic_flag_of_russia__1_,0),
    ZAR(R.drawable.ic_flag_of_russia__1_,0),
    KRW(R.drawable.ic_flag_of_russia__1_,0),

}
